### ISSUE TITLE
Does packet type have two groups values in binary?

### ISSUE THREAD

**Issue by googollee** [socketio/engine.io-protocol#23]
I'm the author of go-socket.io. I try to catch up current implement now. And I have some questions need to clarify. 

As protocol described not very clear, if a packet is string, the leading type id is "4" in string. And if a packet is binary, the leading type id is a byte 4. Am I right?

So it can use type id to check if a packet is string or binary. Right?

And from implement, it seems only message(type 4) packet could be binary packet. All other types packet are string. So it only have types below:
- "0": open
- "1": close
- "2": ping
- "3": pong
- "4": string message
- byte 4: binary message
- "5": upgrade
- "6": noop

Is it right?

**Comment by darrachequesne** [comment]
Yes, it is :+1:
