### ISSUE TITLE
Is 'sid' parameter designed for reconnecting?

### ISSUE THREAD

**Issue by tankcong** [socketio/engine.io-protocol#24]
> sid: if the client has been given a session id, it must be included in the querystring.

I'm connecting server without this param and it works well, so I'm wondering is this parameter just designed for reconnecting?

Thanks.

**Comment by darrachequesne** [comment]
The `sid` is sent by the server as part of the handshake data, and is needed for following calls. Else you should get HTTP 400 response with error [UNKNOWN_SID](https://github.com/socketio/engine.io/blob/1.8.2/lib/server.js#L83).
