### ISSUE TITLE
EIO and t

### ISSUE THREAD

**Issue by akzi** [socketio/engine.io-protocol#27]
http://127.0.0.1:3000/socket.io/?EIO=3&transport=polling&t=Lci8wa9&sid=0VstkFt2SKGr0s2WAAAC
what EIO and t mean?

**Comment by darrachequesne** [comment]
- `EIO` should refer to the version of the Engine.IO protocol
- `t` is an hashed timestamp (for cache-busting)

You mean, that is not documented?

**Comment by akzi** [comment]
thanks , 
http://127.0.0.1:3000/socket.io/?EIO=3&transport=polling&t=LcigZCA
server response something back, but I can't find document to understand this.

**Comment by PapiCZ** [comment]
Does some1 how to generate that hashed timestamp?

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io-protocol/commit/725d551b75f00827f639bfd0666b6145ed948cfb
