### ISSUE TITLE
Does this support fetch? 

### ISSUE THREAD

**Issue by quantuminformation** [socketio/engine.io-protocol#29]

**Comment by darrachequesne** [comment]
@QuantumInformation may I ask what you mean exactly by "fetch"?

**Comment by QuantumInformation** [comment]
Engine uses XHR, so I was wondering if it could use the fetch api too?

**Comment by darrachequesne** [comment]
I guess you're referring to https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API.

I'm not very familiar with it, what additional feature would it bring?

**Comment by QuantumInformation** [comment]
Its pretty much the way all requests are moving too.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
