### ISSUE TITLE
Payload encoding is unclear

### ISSUE THREAD

**Issue by jroper** [socketio/engine.io-protocol#30]
The description of how payloads are encoded is unclear. In particular, how lengths should be encoded is not clear, there is conflicting information, and information that doesn't make sense.

Here are some unanswered questions that the spec leaves begging:

* What is the length when the payload is binary encoded (ie, when XHR2 is supported)? Is it the number of bytes? Is it the number of bytes + 1? Previously, for non XHR2 requests, the length is defined as the number of characters, does that apply to XHR2 requests, or for XHR2 requests is it always the number of bytes?
* For non XHR2 request, should be "b" for binary packets be included in the length or not? If so, then when it says that the length should be the length of the base64 encoded data + 1, that's wrong, because it's +1 for UTF8 packets, but +2 for binary packets.

**Comment by darrachequesne** [comment]
Long overdue, but some example were added: https://github.com/socketio/engine.io-protocol/commit/725d551b75f00827f639bfd0666b6145ed948cfb
