### ISSUE TITLE
Lack of Version History

### ISSUE THREAD

**Issue by awilhite** [socketio/engine.io-protocol#31]
There should be a branch for each version of the protocol, as there are branches on the engine.io repository for 3.1.x, 2.1.x, etc. I have found it extremely frustrating to develop a client implementation without this necessary information.

**Comment by darrachequesne** [comment]
Long overdue, but the following branches were created:

- https://github.com/socketio/engine.io-protocol/tree/v2
- https://github.com/socketio/engine.io-protocol/tree/v3
