### ISSUE TITLE
Wrong about the ping description

### ISSUE THREAD

**Issue by luhui** [socketio/engine.io-protocol#32]
In fact, the pong message doesn't contain the message send in ping

Where we can find the pong implement in [engine.io](https://github.com/socketio/engine.io/blob/b1fa020675d905905b6f07d0a6b5acff775c4be5/lib/socket.js#L100):

```
switch (packet.type) {
      case 'ping':
        debug('got ping');
        this.sendPacket('pong');
        this.emit('heartbeat');
        break;
}
```

As we can see, it just send the pong message and ignore the ping payload.

Should update document like below:

```diff
- Sent by the client. Server should answer with a pong packet containing the same data
+ Sent by the client. Server should answer with a pong packet

client sends: 2probe
- server sends: 3probe
+ server sends: 3
```

Or change the implement of engine.io to fix this issues?

**Comment by darrachequesne** [comment]
If I understand correctly, `ping/pong` events are also used during [probe](https://github.com/socketio/engine.io/blob/3.1.5/lib/socket.js#L198):
```
if ('ping' === packet.type && 'probe' === packet.data) {
      transport.send([{ type: 'pong', data: 'probe' }]);
```
So the example is correct I think. We may add:

```
// during probing
client sends: 2probe
server sends: 3probe
// classic ping/pong
client sends: 2
server sends: 3
```

But I don't know why those probes were not given their own packet types.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
