### ISSUE TITLE
question about packet type id

### ISSUE THREAD

**Issue by wangduanduan** [socketio/engine.io-protocol#33]
what the packet type 42, 428, 429, 4210 mean?

i know 4 is a message, but the 2, 28, 29, 210 ？？

![image](https://user-images.githubusercontent.com/16631306/68172259-cae7e480-ffb1-11e9-9ef5-38e1aca362a4.png)

**Comment by darrachequesne** [comment]
This is the result of the encoding done at the Socket.IO level (see [here](https://github.com/socketio/socket.io-protocol)) and then at the Engine.IO level (this repo).

I'll add some examples here: https://github.com/socketio/socket.io-protocol
