### ISSUE TITLE
Question: is EIO query param used by engine.io?

### ISSUE THREAD

**Issue by Benedicht** [socketio/engine.io-protocol#34]
I couldn't find any reference to it in the source. If it has no use, can it be left out?

**Comment by darrachequesne** [comment]
No, the EIO query param is not used per se.

This query param can can be used during a migration though, in order to route the requests of the client towards the Engine.IO servers in v3 (`?EIO=3`) or the Engine.IO servers in v4 (`?EIO=4`).
