### ISSUE TITLE
Question: is there any way to detect the used engine.io version?

### ISSUE THREAD

**Issue by Benedicht** [socketio/engine.io-protocol#35]
I have a c# implementation that should work with both v3 and v4. Because v4 has a few breaking changes, i can't implement them in a backward compatible way and different code must be executed based on the version of the server.

**Comment by Benedicht** [comment]
A future proof solution would be if the handshake data would contain an additional version field. If it's missing than it's most probably a server using v3 otherwise its value is the version that i (and maybe other too) could use.

**Comment by darrachequesne** [comment]
You should be able to detect the version of the Engine.IO server based on the format of the handshake packet:

```
// v3
96:0{"sid":"lv_VI97HAXpY6yYWAAAC","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":5000}
// v4
0{"sid":"lv_VI97HAXpY6yYWAAAC","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":5000}
```

Details:
- https://github.com/socketio/engine.io-protocol#payload
- https://github.com/socketio/engine.io-protocol/tree/v3#payload

**Comment by Benedicht** [comment]
Thanks, that could work. Any advice for a websocket only session?

**Comment by darrachequesne** [comment]
The first WebSocket frame sent by the server will contain the handshake packet, so you should be able to make the same distinction as above.

![Screenshot from 2020-11-12 15-04-51](https://user-images.githubusercontent.com/13031701/98949807-7cd8bb80-24f8-11eb-87a0-a403da6e3e82.png)

**Comment by Benedicht** [comment]
AFAIK it's the same for v3 and v4.

These are received from different versions:
>0{"sid":"iEDbJrPFWsgeDYk-AAAB","upgrades":[],"pingInterval":25000,"pingTimeout":5000}
>0{"sid":"nR4WsvYPR1J8XrSvAAAA","upgrades":[],"pingInterval":25000,"pingTimeout":5000}

**Comment by darrachequesne** [comment]
Arf, you are right.

For a WebSocket-only session, I think the only difference is the encoding of a binary packet. The packet is prefixed with "4" in v3, whereas it is sent as is in v4.

**Comment by Benedicht** [comment]
Yep, but that's hard to use to decide whether it's v3 or v4, because "4" can be part of the binary data too.

**Comment by Benedicht** [comment]
@darrachequesne Any chance to include something in the handshake payload that would indicate the version of the protocol?

**Comment by darrachequesne** [comment]
We could check the value of the `EIO` query parameter on the server-side, and return a HTTP 400 if the query param is provided but does not match the value of the server. What do you think?

**Comment by Benedicht** [comment]
Hey, sorry for the late reply! 

My only real objection is that it would add additional round-trips, but otherwise it seems good.

**Comment by darrachequesne** [comment]
The server now supports v3 and v4 clients: https://github.com/socketio/engine.io/commit/663d326d18de598318bd2120b2b70cd51adf8955 (included in `engine.io@4.1.0` & `socket.io@3.1.0`).
