### ISSUE TITLE
Question about which side sends `upgrade` message.

### ISSUE THREAD

**Issue by googollee** [socketio/engine.io-protocol#37]
In the front, I'm not an English native speaker. It may be my misunderstanding. I just want to make it clear.

In [Sample session](https://github.com/socketio/engine.io-protocol/tree/master#sample-session), WebSocket frames show

```
...
> 5         => "upgrade" packet type
...
> 2         => "ping" packet type
```

As `ping` is always sent by server-side and they share the same direction, I read it as `upgrade` is sent by server-side too. (That direction is different from what it is in [the next session](https://github.com/socketio/engine.io-protocol/tree/master#sample-session-with-websocket-only), but it doesn't relate with this question.)

In [Transport Upgrading](https://github.com/socketio/engine.io-protocol/tree/master#transport-upgrading), it says

> A connection always starts with polling (either XHR or JSONP). WebSocket gets tested on the (client) side by sending a probe. If the probe is responded from the server, an upgrade packet is sent (from which side? Client?).

As it says `When the server receives the upgrade packet` in the following paragraphs, it conflicts with `WebSocket frames`.

Could you clarify that the upgrade is sent from client and update the WebSocket frames?

**Comment by darrachequesne** [comment]
You are absolutely right, I've updated the documentation in https://github.com/socketio/engine.io-protocol/commit/39c138a1b54567c18f26da09ad6c07499dc0f0a0. Thanks :+1:
