### ISSUE TITLE
Question about long polling and duplicate poll requests

### ISSUE THREAD

**Issue by MSE99** [socketio/engine.io-protocol#38]
In `test-suite.js` there's a test that checks if the server closes the session and sends a `1` close packet when the client makes duplicate poll requests at the same time [here](https://github.com/socketio/engine.io-protocol/blob/main/test-suite/test-suite.js#L293), I have two questions about that:

1. Why is it a problem that the client can make duplicate poll requests?
2. What is the best way for a server to detect that the client made a duplicate poll request i was thinking of doing something with a timestamp we can attach a timestamp to the session and check it when the client makes a poll request.

I'm making my own engine.io implementation and I never done something like this before so i apologize for my ignorance, thanks :).

**Comment by darrachequesne** [comment]
Hi!

> 1. Why is it a problem that the client can make duplicate poll requests?

That's a great question. I think that this is to ensure the ordering of the packets. Also, what would be the benefit of multiple long-polling requests?

> 2. What is the best way for a server to detect that the client made a duplicate poll request

You need to make sure the HTTP request effectively acquires a read lock. In the Node.js implementation, the ongoing HTTP request is stored in the `socket.transport` object: https://github.com/socketio/engine.io/blob/917d1d29e13f2e8f523c3738f6413f67b587aebe/lib/transports/polling.ts#L18

> I'm making my own engine.io implementation

That's awesome! Do not hesitate if something is not clear enough :+1:
