### ISSUE TITLE
Binary messages should be of a different packet type to plaintext messages.

### ISSUE THREAD

**Issue by vxern** [socketio/engine.io-protocol#39]
Due to the nature of data being transmitted, message packets with a binary payload need different handling (identifying, encoding, decoding). This is already being done, but the specification attempts to make these types agree by *attempting* to bunch them together under a single packet `message` with ID `4`, but the same specification, on the other hand, also identifies binary packets differently (using a `b` character).

So, given that not only are the packets handled differently, stored differently, but also is identified differently and transmitted differently (binary packets have MIME type `application/octet-stream`, text packets have MIME type `text/plain`), wouldn't it simply make more sense to have two message packet types, rather than trying hard to make them coexist under a single packet type as is currently being done?

**Comment by darrachequesne** [comment]
Hi! Thanks for opening this :+1: 

I'm not sure about what you are suggesting, what would be the benefits of having two distinct packet types?

**Comment by vxern** [comment]
For all intents and purposes, they already are distinct, it's just that the specification doesn't make that clear:
- They have different IDs: `b` for binary, `4` for text.
- They are encoded differently: `base64` for binary, `utf8` for text.
- They impact the `Content-Type` header value differently: `application/octet-stream` for binary, `text/plain` for text.

**Comment by vxern** [comment]
Alternatively to having different types, whether the message packet was binary or text could have been originally identified within the packet itself using some kind of flag, thus eliminating the need for a different packet type. For example, text message packets would become `40`, binary packets would become `41`. However, this isn't the case, and the specification instead opted for different packet IDs, it just didn't point this out clearly.

**Comment by darrachequesne** [comment]
I think this can be closed now. Please reopen if needed.
