### ISSUE TITLE
Documentation suggestion - explicitly identify text character encoding as UTF8

### ISSUE THREAD

**Issue by EagleAglow** [socketio/engine.io-protocol#42]
I found in the comments to issue #39 that "[packets]... are encoded... utf8 for text".  

I think it would be helpful to add to https://github.com/socketio/engine.io-protocol#packet-encoding

"Packet encoding"

The serialization of an Engine.IO packet depends on the type of the payload (plaintext or binary) and on the transport.

Character encoding is UTF8 for plaintext and for base64-encoded binary payloads.

**Comment by darrachequesne** [comment]
Added in https://github.com/socketio/engine.io-protocol/commit/f21de7b00ed09b3bbad2807db718ea5d6bc36aba.

Thanks!
