### ISSUE TITLE
Isn't it a `ping` packet that the client waiting for?

### ISSUE THREAD

**Issue by shuai-z** [socketio/engine.io-protocol#43]
> Conversely, if the client does not receive a `pong` packet within pingInterval + pingTimeout, then it SHOULD consider that the connection is closed.

The Hearbeat section says, server send `ping` to client, then the client reply a `pong` to server. So the client should wait for a `ping` packet, is it a typo or?

**Comment by darrachequesne** [comment]
Good catch! This is fixed by https://github.com/socketio/engine.io-protocol/commit/c815579e1bfe59a7829f2114752ef78835dafa02.
